In [23]:
import numpy as np
import pandas as pd
from scipy.stats import binom
from numpy.random import default_rng

## Exercise 2.1 

a) P(B|A) > P(B)

b) P(B|A) < P(B)

c) P(B|A) > P(B)

d) P(B|A) > P(B)

## Exercise 2.2

a) P(B|A) = 0.73

b) P(A) = 0.20

c) P(D) = 0.15

d) P(D|C)  = 0.91

e) P(F && E) = 0.38

f) P(E|F) = 0.95

## Exercise 2.3

a) I dont believe the number of babies born each hour is independant of the hour. besides its not binomial in character more likely poission. 

b) bin(27,0.9). 

c) Not binimoial in character,  once she succeeds she cannot try again.

d) Not binomial in character

e) not binomial in chracter.

f) bin (60, 0.8)

## Exercise 2.4

P(Vampires | sparkled ) = P(sparkled | vampire) * P(vampire) / P(sparkled)
 


In [2]:
p_sparkled = 0.7*.05 + .03*.95

In [5]:
p_vampires = .7*.05/p_sparked
p_vampires

0.5511811023622046

## Exercise 2.5


In [6]:
# a)
p_mold = 0.18

b)

P(Maple) = P(Maple | Mold) * P(Mold) + P(Maple | No Mold) * P(No Mold)

In [8]:
p_maple = 0.8*p_mold + .1*(1-p_mold)
p_maple

0.226

c)

In [10]:
p_mold_given_maple = 0.8*p_mold / p_maple
p_mold_given_maple

0.6371681415929202

d)  Learning that is maple increased the probability of the tree haven mold significantly.

## Exercise 2.6 

P(likes | less then 4 stars) = P(less then 4 stars | likes) * P(likes) /P(less then 4 stars)

We need to know how many resteraunts have less then 4 stars in general, or at least what are the fraction of resteraunts she doesnt like that have less then 4 stars. We dont know this so cannot use law of total probability for example.

## Exercise 2.13

a) Posterior model has significant increase for 0.6 and maybe 0.4.  All others decreased.  So lets try: 

0.4: 0
0.5: 0.2
0.6: 0.7
0.7: 0.1

total = 1.0

b) Calculate the posteiror model:


In [12]:
prior = [(0.4, 0.1), (0.5, 0.2), (0.6, .44), (0.7, 0.26)]
posterior_unnorm = [binom.pmf(47, 80, pi ) * prior_prob for (pi, prior_prob) in prior]

In [15]:
posterior_unnorm /np.sum(posterior_unnorm)

array([6.49128771e-04, 1.13540381e-01, 8.33798600e-01, 5.20118903e-02])

In [16]:
prior = [(0.4, 0.1), (0.5, 0.2), (0.6, .44), (0.7, 0.26)]
posterior_unnorm = [binom.pmf(470, 800, pi ) * prior_prob for (pi, prior_prob) in prior]
posterior_unnorm /np.sum(posterior_unnorm)

array([5.05556742e-26, 2.64663968e-06, 9.99997353e-01, 1.01561140e-10])

## Exercise 2.15

a) The distribution would be more skewed to the right

b) opposite of above.

c) 

In [19]:
prior = [(0.6, 0.3), (0.65, 0.4), (0.7, .2), (0.75, 0.1)]
posterior_unnorm = [binom.pmf(10, 15, pi ) * prior_prob for (pi, prior_prob) in prior]
posterior_unnorm /np.sum(posterior_unnorm)

array([0.28107455, 0.42797815, 0.20773252, 0.08321478])

d) I think she would have to conclude that she didnt collect enough data to change what was known from previous research?

## Exercise 2.16
Sick tree simulation

In [70]:
# data frame, 'Mold' and 'Type'. 

rng = default_rng(33)

p_mold = 0.18

trees = ["Elm", "Maple", "Other"]

p_type_inf = [0.15, 0.8, 0.05]
p_type_clear = [0.2, 0.10, 0.7]

trees_sample = pd.DataFrame(data = {'Mold' : [p < p_mold for p in rng.random(10000)] })

def choose_tree(mold):
    if mold:
        return rng.choice(trees, 1, p=p_type_inf)[0]
    else:
        return rng.choice(trees, 1, p=p_type_clear)[0]


trees_sample['Type'] = trees_sample['Mold'].apply(choose_tree)

# trees_sample  = [ (p < p_mold, rng.choice(trees, 1,\
#                   p= (p_type_inf if p < p_mold else p_type_clear))[0] ) for p in rng.random(10000)]
 

In [71]:
np.sum([1 for tree in [choose_tree(True) for x in range(10000)] if tree == 'Maple'])

8045

In [72]:
trees_sample

Mold   Type
0     False  Other
1     False  Other
2     False  Other
3     False    Elm
4     False  Other
...     ...    ...
9995   True  Maple
9996  False  Other
9997  False    Elm
9998  False  Other
9999  False    Elm

[10000 rows x 2 columns]

In [73]:
maples = trees_sample[trees_sample['Type']=='Maple']
p_mold_given_maple = len(maples[maples['Mold']])/len(maples)
p_mold_given_maple

0.653557224922669

In [74]:
len(maples)/10000

0.2263

Matches well !

## Exercise 2.18

In [78]:
# data frame

rng = default_rng(33)

pi =  [0.4, 0.5, 0.6, 0.7]

prior = [0.1, 0.2, 0.44, 0.26]

samples = pd.DataFrame(data = {'pi' : rng.choice(pi, 10000, p = prior)})
samples['Count'] = samples['pi'].apply(lambda p: rng.binomial(80,p))



In [79]:
samples

pi  Count
0     0.6     45
1     0.6     51
2     0.7     61
3     0.5     35
4     0.6     50
...   ...    ...
9995  0.4     30
9996  0.6     55
9997  0.6     50
9998  0.7     56
9999  0.7     54

[10000 rows x 2 columns]

Ok of those, we now find the ones that have exactly 47 

In [83]:
consistent_with_data = samples[samples['Count']==47].reset_index(drop=True)

In [88]:
counts =consistent_with_data.groupby(['pi']).count()

In [89]:
counts.sum()

Count    444
dtype: int64

In [99]:
counts['Post_frac'] = counts['Count'] / counts.sum()[0]

In [100]:
counts

Count  Post_frac
pi                   
0.5     54   0.121622
0.6    361   0.813063
0.7     29   0.065315

## Exercise 2.19
This is basically the same as 2.18

In [102]:
# data frame

rng = default_rng(33)

pi =  [0.6, 0.65, 0.7, 0.75]

prior = [0.3, 0.4, 0.2, 0.1]

samples = pd.DataFrame(data = {'pi' : rng.choice(pi, 10000, p = prior)})
samples['Count'] = samples['pi'].apply(lambda p: rng.binomial(15,p))

post_counts = samples[samples['Count']==10].reset_index(drop=True).groupby(['pi']).count()


In [103]:
 post_counts['Count'] / post_counts.sum()[0]

pi
0.60    0.296891
0.65    0.423270
0.70    0.196590
0.75    0.083250
Name: Count, dtype: float64

same conclusion, almost no effect

## Exercise 2.20

 Whether you like it or not, cats have taken over the internet.23 Joining the craze, Zainab has written an algorithm to detect cat images. It correctly identifies 80% of cat images as cats, but falsely identifies 50% of non-cat images as cats. Zainab tests her algorithm with a new set of images, 8% of which are cats. What’s the probability that an image is actually a cat if the algorithm identifies it as a cat? Answer this question by simulating data for 10,000 images

In [113]:
rng = default_rng(33)

cats = pd.DataFrame(data = {'isCat' : [p < .08 for p in rng.random(10000)]})

def cat_test(is_cat):
    if is_cat:
        return rng.random() < 0.8
    else:
        return rng.random() < 0.5

cats["IdentifiedAsCat"] = cats['isCat'].apply(cat_test)

tested_true = cats[cats["IdentifiedAsCat"]].reset_index(drop=True)

In [115]:
len(tested_true[tested_true['isCat']])/len(tested_true)

0.13212982523526023

## Exercise 2.21

A medical test is designed to detect a disease that about 3% of the population has. For 93% of those who have the disease, the test yields a positive result. In addition, the test falsely yields a positive result for 7% of those without the disease. What is the probability that a person has the disease given that they have tested positive? Answer this question by simulating data for 10,000 people.


In [121]:
rng = default_rng(33)

people = pd.DataFrame(data = {'isSick' : [p < .03 for p in rng.random(10000)]})

def disease_test(is_sick):
    if is_sick:
        return rng.random() < 0.93
    else:
        return rng.random() < 0.07

people["tested_positive"] = people['isSick'].apply(disease_test)

tested_true = people[people["tested_positive"]].reset_index(drop=True)

In [122]:
len(tested_true[tested_true['isSick']])/len(tested_true)

0.3083511777301927